services:
  - type: web
    name: eapce27-laravel
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://eapce27-laravel.onrender.com
      - key: APP_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: eapce27-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: eapce27-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: eapce27-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: eapce27-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: eapce27-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file

databases:
  - name: eapce27-db
    plan: free
    databaseName: eapce27
